{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyP4NozWaSdQkq6c4LVfSywR"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"1OLL7gQkE0KF","executionInfo":{"status":"ok","timestamp":1664570777155,"user_tz":420,"elapsed":34299,"user":{"displayName":"Louis Barbier","userId":"02249234305114210027"}},"outputId":"2055d793-91fb-442d-fc56-cdf4d7ad856c"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"code","source":["# from keras.preprocessing.image import load_img \n","# from keras.preprocessing.image import img_to_array \n","# from keras.applications.vgg16 import preprocess_input \n","\n","# # models \n","# from keras.applications.vgg16 import VGG16 \n","# from keras.models import Model\n","# from keras.models import Sequential\n","# from keras import Input\n","# from keras import layers\n","# # clustering and dimension reduction\n","# from sklearn.cluster import KMeans\n","# from sklearn.decomposition import PCA\n","\n","# import tensorflow as tf\n","\n","# # for everything else\n","import os\n","# import numpy as np\n","# import matplotlib.pyplot as plt\n","# from random import randint\n","# import pandas as pd\n","# import pickle\n","\n","import tensorflow as tf\n","from tensorflow import keras\n","from tensorflow.keras import layers\n","\n","from keras.preprocessing.image import ImageDataGenerator\n","\n","import tensorflow_datasets as tfds"],"metadata":{"id":"ljDQjE89FNNH","executionInfo":{"status":"ok","timestamp":1664570799618,"user_tz":420,"elapsed":4409,"user":{"displayName":"Louis Barbier","userId":"02249234305114210027"}}},"execution_count":3,"outputs":[]},{"cell_type":"code","source":["path = r\"/content/drive/MyDrive/HARP_DATASET/1_day_image/square_images_size224\"\n","os.chdir(path)\n","\n","spectrograms = []\n","\n","with os.scandir(path) as files:\n","    for file in files:\n","        if file.name.endswith('.png'):\n","            spectrograms.append(file.name)\n","\n","print(len(spectrograms))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"adGXJpmTFQH6","executionInfo":{"status":"ok","timestamp":1664570816118,"user_tz":420,"elapsed":13678,"user":{"displayName":"Louis Barbier","userId":"02249234305114210027"}},"outputId":"1ad35e67-f495-4657-99f9-52862f33ef7a"},"execution_count":4,"outputs":[{"output_type":"stream","name":"stdout","text":["3269\n"]}]},{"cell_type":"code","source":["initial_model = keras.Sequential(\n","    [\n","      layers.Rescaling(1./255, input_shape=(256, 256, 3)),\n","      layers.Conv2D(16, 3, padding='same', activation='relu'),\n","      layers.MaxPooling2D(),\n","      layers.Conv2D(32, 3, padding='same', activation='relu'),\n","      layers.MaxPooling2D(),\n","      layers.Conv2D(64, 3, padding='same', activation='relu'),\n","      layers.MaxPooling2D(),\n","      layers.Flatten(),\n","      layers.Dense(128, activation='relu'),\n","    ]\n",")\n","\n","feature_extractor = keras.Model(\n","    inputs=initial_model.inputs,\n","    outputs=[layer.output for layer in initial_model.layers],\n",")\n","\n","# Call feature extractor on test input.\n","x = tf.ones((1, 256, 256, 3))\n","features = feature_extractor(x)\n"],"metadata":{"id":"ndNwb4JAFcGF","executionInfo":{"status":"ok","timestamp":1664570830154,"user_tz":420,"elapsed":1275,"user":{"displayName":"Louis Barbier","userId":"02249234305114210027"}}},"execution_count":5,"outputs":[]},{"cell_type":"code","source":["train_dataset = tf.keras.preprocessing.image_dataset_from_directory(path,label_mode=None,batch_size=100, validation_split=0.2, subset=\"training\", seed = 22,image_size=(256, 256))\n","validation_dataset = tf.keras.preprocessing.image_dataset_from_directory(path,label_mode=None,batch_size=100, validation_split=0.2, subset=\"validation\", seed = 22,image_size=(256, 256))\n","\n","AUTOTUNE = tf.data.AUTOTUNE\n","\n","train_dataset = train_dataset.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)\n","validation_dataset = validation_dataset.cache().prefetch(buffer_size=AUTOTUNE)\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"1rCAupFZHu__","executionInfo":{"status":"ok","timestamp":1664577044777,"user_tz":420,"elapsed":505,"user":{"displayName":"Louis Barbier","userId":"02249234305114210027"}},"outputId":"d4739766-c593-4d01-85d0-7fe3c3941566"},"execution_count":33,"outputs":[{"output_type":"stream","name":"stdout","text":["Found 3393 files belonging to 1 classes.\n","Using 2715 files for training.\n","Found 3393 files belonging to 1 classes.\n","Using 678 files for validation.\n"]}]},{"cell_type":"code","source":["initial_model.compile(optimizer='adam',loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])"],"metadata":{"id":"Hv5jGZZUHpG-","executionInfo":{"status":"ok","timestamp":1664577050380,"user_tz":420,"elapsed":198,"user":{"displayName":"Louis Barbier","userId":"02249234305114210027"}}},"execution_count":35,"outputs":[]},{"cell_type":"code","source":["epochs = 10\n","batch_size = 50\n","history = initial_model.fit(train_dataset, epochs=epochs,\n","                    batch_size=batch_size,\n","                    shuffle=True,\n","                    validation_data=validation_dataset,\n","                    verbose=1)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"pydtk7qmuWst","executionInfo":{"status":"error","timestamp":1664577412955,"user_tz":420,"elapsed":219,"user":{"displayName":"Louis Barbier","userId":"02249234305114210027"}},"outputId":"2510595c-537a-4ad2-901d-5fbf0650f2f6"},"execution_count":37,"outputs":[{"output_type":"stream","name":"stdout","text":["Epoch 1/10\n"]},{"output_type":"error","ename":"ValueError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-37-ba31848585ec>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      5\u001b[0m                     \u001b[0mshuffle\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m                     \u001b[0mvalidation_data\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mvalidation_dataset\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m                     verbose=1)\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     65\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 67\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     68\u001b[0m     \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m       \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py\u001b[0m in \u001b[0;36mautograph_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m   1145\u001b[0m           \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint:disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1146\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mhasattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"ag_error_metadata\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1147\u001b[0;31m               \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mag_error_metadata\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mto_exception\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1148\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1149\u001b[0m               \u001b[0;32mraise\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: in user code:\n\n    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 1021, in train_function  *\n        return step_function(self, iterator)\n    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 1010, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 1000, in run_step  **\n        outputs = model.train_step(data)\n    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 861, in train_step\n        self._validate_target_and_loss(y, loss)\n    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 819, in _validate_target_and_loss\n        'Target data is missing. Your model was compiled with '\n\n    ValueError: Target data is missing. Your model was compiled with loss=<keras.losses.SparseCategoricalCrossentropy object at 0x7f5c20474c50>, and therefore expects target data to be provided in `fit()`.\n"]}]}]}